e-ticaret/e-ticaret/Models/Slider.cs
using System;
using System.Collections.Generic;

namespace e_ticaret.Models
{
    public partial class Slider
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Resim { get; set; }
        public string BaslikIcerik { get; set; }
        public string BaslikEk { get; set; }
        public string ButtonName { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}

e-ticaret/e-ticaret/Controllers/ShopController.cs
using e_ticaret.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_ticaret.Controllers
{
    public class ShopController : Controller
    {
        eTicaretContext db = new eTicaretContext();
        public ActionResult Index()
        {

            Session["DilID"] = "1";

            return View();

        }

        public ActionResult Contact()
        {
            using (eTicaretContext db = new eTicaretContext())
            {
                int d = int.Parse(Session["DilID"].ToString());
                return View(db.SiteBilgileris.Where(p => p.DilID == d).ToList());
            }

        }

        public ActionResult About()
        {
            using (eTicaretContext db = new eTicaretContext())
            {
                int d = int.Parse(Session["DilID"].ToString());
                return View(db.Metinlers.Where(p => p.DilID == d).ToList());
            }

        }

        public ActionResult Slider()
        {
            using (eTicaretContext db = new eTicaretContext())
            {
                List<e_ticaret.Models.Slider> slider = db.Sliders.ToList();
                return PartialView("Slider", slider);
            }
        }

        public ActionResult Sepetim()
        {
            string a = Request.Cookies["visitorS"].Value;
            int d = int.Parse(Session["DilID"].ToString());
            ViewBag.Sepet = db.Sepets.Where(s => s.Cookie == a && s.Aktif == true).ToList();
            return View(db.SiteBilgileris.Where(x => x.DilID == d).ToList());
           
        }
        public ActionResult Blog()
        {
            int d = int.Parse(Session["DilID"].ToString());
            return PartialView(db.BlogHaberLs.Where(x => x.DilID == d).ToList());
           
        }
        public ActionResult InstagramList()
        {
            int d = int.Parse(Session["DilID"].ToString());
            return PartialView();

        }
        public ActionResult PromosyonBanner()
        {

            return PartialView("PromosyonBanner");
        }

        public ActionResult PromosyonBannerDortlu()
        {

            using (eTicaretContext db = new eTicaretContext())
            {
                List<e_ticaret.Models.Promosyon> promosyonDortlu = db.Promosyons.ToList();
                return PartialView("PromosyonBannerDortlu", promosyonDortlu);
            }

        }

        private string GetClientIp()
        {
            var ip = string.Empty;
            if (System.Web.HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"] != null)
            {
                ip = System.Web.HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"].ToString();
            }
            else if (System.Web.HttpContext.Current.Request.ServerVariables["HTTP_CLIENT_IP"] != null && System.Web.HttpContext.Current.Request.ServerVariables["HTTP_CLIENT_IP"].Length != 0)
            {
                ip = System.Web.HttpContext.Current.Request.ServerVariables["HTTP_CLIENT_IP"];
            }
            else if (System.Web.HttpContext.Current.Request.UserHostAddress.Length != 0)
            {
                ip = System.Web.HttpContext.Current.Request.UserHostName;
            }
            return ip;
        }

        public ActionResult HeaderTopBar()
        {

            HttpCookie cokie;
            cokie = Request.Cookies["visitorS"];
            if (cokie == null)
            {
                cokie = new HttpCookie("visitorS", GetClientIp());
                Response.Cookies.Add(cokie);
            }
            string a = Request.Cookies["visitorS"].Value;
            int d = int.Parse(Session["DilID"].ToString());
            ViewBag.Sepet = db.Sepets.Where(s=> s.Cookie==a && s.Aktif==true).ToList();
            ViewBag.Diller = db.Dils.Where(x => x.Aktif == true).ToList();
            return PartialView("HeaderTopBar", db.SiteBilgileris.Where(x => x.DilID == d).ToList());

        }

        public ActionResult Fotter()
        {
            int d = int.Parse(Session["DilID"].ToString());
            return PartialView("Fotter", db.SiteBilgileris.Where(x => x.DilID == d).ToList());
        }

        public ActionResult DilDegistir(string DilID, string url)
        {
            Session["DilID"] = DilID;
            if (url == null)
            {
                return View();
            }
            else
            {
                return Redirect(url);
            }
        }
    }
}

e-ticaret/e-ticaret/Views/Shop/About.cshtml
@model IEnumerable<e_ticaret.Models.Metinler>
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Root.cshtml";
}

@foreach (var item in Model)
{
    <!-- Page Content Wraper -->
    <div class="page-content-wraper">
        <!-- Bread Crumb -->
        <section class="breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="breadcrumb-link">
                            <a href="/Shop/Index">Home</a>
                            <span>About Us</span>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
        <!-- Bread Crumb -->
        <!-- Page Content -->
        <section class="content-page">
            <div class="container mb-80">
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <div class="row mb-45">
                            <div class="col-sm-12 text-center">
                                <h2 class="normal"><span>@item.GirisYazisiBaslik</span></h2>
                                <p class="large">@item.GirisYazisi</p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <section class="section-padding bg-gray">
                <div class="container text-center mb-45">
                    <div class="row">
                        <div class="col-md-12">
                            <h2 class="normal"><span>What About Us</span></h2>
                            <p class="large">
                                @Html.Raw(item.Hakkimizda)
                            </p>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 mb-xs-30">
                            <h5>Vizyonumuz</h5>
                            @Html.Raw(item.Vizyon)
                        </div>
                        <div class="col-md-4 col-sm-6 mb-xs-30">
                            <h5>Misyonumuz</h5>
                            @Html.Raw(item.Misyon)
                        </div>
                        <div class="col-md-4 col-sm-6">
                            <h5>Stratejimiz</h5>
                            @Html.Raw(item.Strateji)
                        </div>
                    </div>
                </div>
            </section>
            
        </section>
        <!-- End Page Content -->

    </div>
    <!-- End Page Content Wraper -->
}

e-ticaret/e-ticaret/Views/Shop/Blog.cshtml
@model IEnumerable<e_ticaret.Models.BlogHaberL>
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_Root.cshtml";
}
@if (Model.Count() > 0)
{
    <!-- Blog & News -->
    <section class="section-padding">
        <div class="container">
            <h2 class="page-title">Blog & News</h2>
        </div>
        <div class="container">
            <div id="blog-carousel" class="blog-carousel owl-carousel owl-theme nf-carousel-theme1">

                @foreach (var item in Model)
                {
                    <div class="product-item">
                        <div class="blog-box">
                            <div class="blog-img-wrap">
                                <img src="~/Content/img/blog/@item.Resim" alt="@item.Baslik" />
                            </div>
                            <div class="blog-box-content">
                                <div class="blog-box-content-inner">
                                    <h4 class="blog-title"><a href="#">@item.Baslik</a></h4>
                                    <p class="info"><span>by <a href="#">@item.Baslik</a></span><span>@item.Tarih</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </section>
    <!-- End Blog & News -->

}

e-ticaret/e-ticaret/Views/Shop/Contact.cshtml
@model IEnumerable<e_ticaret.Models.SiteBilgileri>
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Root.cshtml";
}
@foreach (var item in Model)
{
            <!-- Page Content Wraper -->
    <div class="page-content-wraper">
        <!-- Bread Crumb -->
        <section class="breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="breadcrumb-link">
                            <a href="/Shop/Index">Home</a>
                            <span>Contact Us</span>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
        <!-- Bread Crumb -->
        <!-- Page Content -->
        <section class="content-page">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div id="map" class="map style1 mb-45">@item.HaritaKodu</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 mb-xs-30">
                       <h6>Company address</h6>
                        <p class="mb-25">
                            @item.Adres
                            <br>
                            @item.Ilce,@item.Sehir
                            <br>
                            @item.Ulke
                        </p>
                        <h6>Contact Information</h6>
                        <ul class="Contact-information mb-25">
                            <li><i class="fa fa-envelope" aria-hidden="true"></i>@item.Mail</li>
                            <li><i class="fa fa-phone" aria-hidden="true"></i>@item.Tel</li>
                        </ul>
                        <hr />
                        <div class="product-share mtb-30">
                            <ul class="list-none">
                                <li><a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="http://twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="http://plus.google.com/" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="http://pinterest.com/" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="col-md-6 offset-md-2">
                        <h2 class="normal"><span>Contact Us</span></h2>
                        <form class="Contact-form">
                            <div class="form-field-wrapper">
                                <label>Your Name <span class="required">*</span></label>
                                <input id="author" class="input-md form-full-width" name="author" placeholder=" EnterYour Name (required)" value="" size="30" aria-required="true" required="" type="text">
                            </div>
                            <div class="form-field-wrapper">
                                <label>Your Email <span class="required">*</span></label>
                                <input id="author-email" class="input-md form-full-width" name="author" placeholder="Enter Your Email Address (required)" value="" size="30" aria-required="true" required="" type="email">
                            </div>
                            <div class="form-field-wrapper">
                                <label>Your subject <span class="required">*</span></label>
                                <input id="subject" class="input-md form-full-width" name="author" placeholder="Enter Your Subject (required)" value="" size="30" aria-required="true" required="" type="text">
                            </div>
                            <div class="form-field-wrapper">
                                <label>Comments<span class="required">*</span></label>
                                <textarea id="comment" class="form-full-width" name="comment" placeholder="Enter Your Subject (required)" cols="45" rows="8" aria-required="true" required=""></textarea>
                            </div>
                            <div class="form-field-wrapper">
                                <input name="submit" id="submit" class="submit btn btn-md btn-color" value="Submit" type="submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Page Content -->

    </div>
    <!-- End Page Content Wraper -->
}

e-ticaret/e-ticaret/Views/Shop/Fotter.cshtml
@model IEnumerable<e_ticaret.Models.SiteBilgileri>

@foreach (var veri in Model)
{
    <!-- Footer Info -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 mb-sm-45">
                <div class="footer-block about-us-block">
                    <img src="~/Content/img/logo_white.png" width="125" alt="@veri.FirmaAdi">
                    <p>
                        @foreach (var item in veri.Dil.Metinlers)
                        {
                            if (veri.DilID == item.DilID)
                            {
                                @Html.Raw(item.GirisYazisi)
                            }
                        }
                    </p>
                    <ul class="footer-social-icon list-none-ib">

                        @foreach (var item in veri.Dil.Ayarlars)
                        {
                            if (veri.DilID == item.DilID)
                            {
                                <li><a href="http://facebook.com/@item.FacebookAppID" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="https://twitter.com/@item.TwitterApiID" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="https://www.instagram.com/@item.InstagramID" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            }
                        }
                    </ul>
                </div>
            </div>

            <div class="col-lg-2 col-md-4 col-sm-4 mb-sm-45">
                <div class="footer-block information-block">
                    <h6>Information</h6>
                    <ul>
                        <li><a href="/Shop/About">About Us</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 mb-sm-45">
                <div class="footer-block links-block">
                    <h6>Our Links</h6>
                    <ul>
                        <li><a href="#">Retunrs</a></li>
                        <li><a href="#">Our Sitemap</a></li>
                        <li><a href="#">Terms &amp; Condition</a></li>
                        <li><a href="#">Delivery Information</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-2 col-md-4 col-sm-4 mb-sm-45">
                <div class="footer-block extra-block">
                    <h6>BLOG</h6>
                    <ul>
                        @*<li><a href="#">New Collection</a></li>
                            <li><a href="#">Women Dresses</a></li>
                            <li><a href="#">Kids Collection</a></li>
                            <li><a href="#">Mens Collection</a></li>
                            <li><a href="#">Custom Service</a></li>
                            <li><a href="#">Shipping policy</a></li>*@
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-12 col-sm-12">
                <div class="footer-block contact-block">
                    <h6>Contact</h6>
                    <ul>
                        <li>
                            <i class="fa fa-map-marker" aria-hidden="true"></i>@veri.Adres
                            <br>
                            @veri.Ulke
                        </li>
                        <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:@veri.Mail">@veri.Mail</a></li>
                        <li><i class="fa fa-phone" aria-hidden="true"></i>@veri.Tel</li>
                        <li><i class="fa fa-fax" aria-hidden="true"></i>@veri.Faks</li>




                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer Info -->
                            <!-- Footer Newsletter -->
    <div class="container">
        <div class="footer-newsletter">
            <h4>Subscribe Newsletter</h4>
            <form class="footer-newslettr-inner">
                <input class="input-md fancy" name="footeremail" title="Enter Email Address.." placeholder="Enter Email Address.." type="text">
                <button class="btn btn-md btn-color fancy">Sing Up</button>
            </form>
        </div>
    </div>
                            <!-- End Footer Newsletter -->
                            <!-- Footer Copyright -->
    <div class="container">
        <div class="copyrights">
            <p class="copyright">&copy; Created by <a href="#" target="_blank">Liman HOST</a>. Byte YAZILIM 2017</p>
            <p class="payment">
                <img src="~/Content/img/payment_logos.png" alt="payment">
            </p>
        </div>
    </div>
                            <!-- End Footer Copyright -->
}

e-ticaret/e-ticaret/Views/Shop/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Root.cshtml";
}
@{

    @Html.Action("Slider", "Shop");
    @Html.Action("PromosyonBanner", "Shop");
    @Html.Action("PromosyonBannerDortlu", "Shop");
    @Html.Action("UrunlerAnaSayfa", "Urunler");
    @Html.Action("KategoriContent", "Kategori");
}

@{
    @Html.Action("Blog", "Shop");
}

@*<section class="section-padding dark-bg container-fluid bg-image text-center overlay-black40" data-background-img="img/bg/bg_7.jpg" data-bg-position-x="center top" style="background-image: url(&quot;img/bg/bg_7.jpg&quot;); background-position: center top;">
        <div class="container newsletter section-padding-b">
            <h2 class="page-title">Subscribe To Newsletter</h2>
            <form name="form-newsletter" class="newsletter-from" id="form-newsletter" method="post">
                <div class="form-input">
                    <input class="input-lg" name="frmemail" id="frmemail" placeholder="Enter Email Address..." title="Enter Email Address..." type="text">
                </div>
                <button class="btn btn-lg btn-color">Sing Up</button>
            </form>
            <p class="italic">Sign up For Exclusive Updates, New Arrivals And Insider-Only Discount.</p>
        </div>
    </section>*@

e-ticaret/e-ticaret/Views/Shop/InstagramList.cshtml
<!-- Instagram -->
<section class="section-padding instagram bg-gray">
    <div class="container text-center">
        <h2 class="page-title">Liman Grafik</h2>
        <p class="">Follow Us <a class="strong" href="#">MayShop</a></p>
    </div>
    <div class="container">
        <ul class="intagram-feed">
            <li>
                <a href="#">
                    <img src="~/Content/img/instagram/insta-1.jpg" alt="">
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="~/Content/img/instagram/insta-2.jpg" alt="">
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="~/Content/img/instagram/insta-3.jpg" alt="">
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="~/Content/img/instagram/insta-4.jpg" alt="">
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="~/Content/img/instagram/insta-5.jpg" alt="">
                </a>
            </li>
        </ul>
    </div>
</section>
<!-- End Instagram -->

e-ticaret/e-ticaret/Views/Shop/PromosyonBanner.cshtml
<!-- Promo Box -->
<section id="promo" class="section-padding-sm promo ">
    <div class="container">
        <div class="promo-box row">
            <div class="col-md-4 mtb-sm-30 promo-item">
                <div class="icon"><i class="fa fa-truck" aria-hidden="true"></i></div>
                <div class="info">
                    <a href="#">
                        <h6 class="normal">Delivery Free</h6>
                    </a>
                    <p>On Order Over $150</p>
                </div>
            </div>
            <div class="col-md-4 mtb-sm-30 promo-item">
                <div class="icon"><i class="fa fa-repeat" aria-hidden="true"></i></div>
                <div class="info">
                    <a href="#">
                        <h6 class="normal">Exchange or Return</h6>
                    </a>
                    <p>30 Day Money Back Guarantee</p>
                </div>
            </div>
            <div class="col-md-4 mtb-sm-30 promo-item">
                <div class="icon"><i class="fa fa-headphones" aria-hidden="true"></i></div>
                <div class="info">
                    <a href="#">
                        <h6 class="normal">Support</h6>
                    </a>
                    <p>24/7 Online Support</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Promo Box -->

e-ticaret/e-ticaret/Views/Shop/PromosyonBannerDortlu.cshtml
@model IEnumerable<e_ticaret.Models.Promosyon>

@{
    string ad1 = "", ad2 = "", ad3 = "", ad4 = "", url1 = "", url2 = "", url3 = "", url4 = "", resim1 = "", resim2 = "", resim3 = "", resim4 = "";
    int deger = 1;
}
@foreach (var item in Model)
{
    if (deger == 1)
    {
        ad1 = item.Adi;
        resim1 = item.Resim;
        url1 = item.URL;
    }
    else if (deger == 2)
    {
        ad2 = item.Adi;
        resim2 = item.Resim;
        url2 = item.URL;
    }
    else if (deger == 3)
    {
        ad3 = item.Adi;
        resim3 = item.Resim;
        url3 = item.URL;
    }
    else if (deger == 4)
    {
        ad4 = item.Adi;
        resim4 = item.Resim;
        url4 = item.URL;
    }
    deger++;
}

<!-- Promo Banner -->
<section id="promo-banner" class="section-padding-b">
    <div class="container">
        <div class="row">


            <!--Left Side-->
            <div class="col-md-6">
                <div class="row">


                    <div class="col-12 mb-30">
                        <!-- banner No.1 -->
                        <div class="promo-banner-wrap">
                            <a href="@url1" class="promo-image-wrap">

                                <img src="~/Content/img/banner/@resim1" alt="@ad1" />

                            </a>

                        </div>
                    </div>



                    <div class="col-12 mb-sm-30">
                        <!-- banner No.2 -->
                        <div class="promo-banner-wrap">

                            <a href="@url2" class="promo-image-wrap">

                                <img src="~/Content/img/banner/@resim2" alt="@ad2" />

                            </a>
                        </div>


                    </div>

                </div>

            </div>

            <!--Right Side-->
            <div class="col-md-6">
                <div class="row">

                    <div class="col-12 mb-30">
                        <!-- banner No.3 -->
                        <div class="promo-banner-wrap">
                            <a href="@url4" class="promo-image-wrap">

                                <img src="~/Content/img/banner/@resim4" alt="@ad4" />

                            </a>

                        </div>
                    </div>


                    <div class="col-12 mb-sm-30">
                        <!-- banner No.4 -->
                        <div class="promo-banner-wrap">
                            <a href="@url3" class="promo-image-wrap">

                                <img src="~/Content/img/banner/@resim3" alt="@ad3" />

                            </a>

                        </div>
                    </div>

                </div>

            </div>
            <!-- End Promo Banner -->


        </div>
    </div>
</section>